services:
  postgres:
    image: postgres:16
    container_name: edu_dbt_prj_postgres
    environment:
      POSTGRES_USER: edu
      POSTGRES_PASSWORD: edu
      POSTGRES_DB: edu_warehouse
    ports:
      - "6543:5432"
    volumes:
      - ./warehouse/ddl:/ddl
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
